//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PelotonIDE.Strings.en {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JavaScriptLibraries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JavaScriptLibraries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PelotonIDE.Strings.en.JavaScriptLibraries", typeof(JavaScriptLibraries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * 
        /// *   real-turtle v1.1.6
        /// *   https://github.com/leonceaklin/real-turtle
        /// *
        /// *   Copyright (c) Léonce Aklin
        /// *
        /// *   This source code is licensed under the MIT license found in the
        /// *   LICENSE file in the root directory of this source tree.
        /// *
        /// */
        ///!function(t,e){&quot;object&quot;==typeof exports&amp;&amp;&quot;object&quot;==typeof module?module.exports=e():&quot;function&quot;==typeof define&amp;&amp;define.amd?define([],e):&quot;object&quot;==typeof exports?exports.RealTurtle=e():t.RealTurtle=e()}(self,(()=&gt;(()=&gt;{var t={766:(t,e,r)=&gt;{&quot;use str [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string real_turtle {
            get {
                return ResourceManager.GetString("real-turtle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (()=&gt;{let e=window.RealTurtle.default;var t=document.getElementById(&quot;real-turtle&quot;);null==t&amp;&amp;((t=document.createElement(&quot;canvas&quot;)).id=&quot;real-turtle&quot;,document.body.append(t),console.warn(&quot;Turtle helper could not find an existing canvas element. Created a custom one&quot;,t)),null!=t.getAttribute(&quot;width&quot;)&amp;&amp;null!=t.getAttribute(&quot;height&quot;)||(t.width=window.innerWidth,t.height=window.innerHeight),window.turtle=new e(t,{verbose:!1,autoStart:!0,state:{speed:.5}});var n=document.createElement(&quot;style&quot;);n.type=&quot;text/css&quot;,n.i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string real_turtle_helpers_simple {
            get {
                return ResourceManager.GetString("real-turtle-helpers-simple", resourceCulture);
            }
        }
    }
}
